apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  generators:
  - git:
    - repoURL: https://github.com/thrinathinfwdcurv/argocd.git
      revision: HEAD
      path: demo
    - repoURL: https://github.com/thrinathinfwdcurv/argocd1.git
      revision: HEAD
      path: demo
  template:
    metadata:
      name: "{{path}}-app"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{revision}}"
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: myapp
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
