apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application-container
          image: thrinathreddy234/argocd:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MY_ENV_VAR
              value: "my-value"
