apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      annotations:
        argocd.argoproj.io/sync-wave: "0"
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: thrinathreddy234/argocd:1.0
        ports:
        - containerPort: 8080
